cache = yes
ontop
save-watch-history = no

hwdec = auto-safe # Decoder
vo=gpu-next # Renderer
# profile=gpu-hq # Preset

# Use extra large RAM cache (needs cache=yes).
#demuxer-max-bytes=500M
#demuxer-max-back-bytes=100M

gpu-api=vulkan
vulkan-device='Intel(R) UHD Graphics (CML GT2)'

# OSD #
osd-font='JetBrains Mono'
osd-font-size=30
osd-bar-align-y=0.6
osd-border-size=3
osd-bar-h=1
osd-bar-w=60

# OSC:  --script-opts=osc-optionA=value1,osc-optionB=value2  #
#script-opts=osc-showwindowed=no # Enable the OSC when windowed. Activates on arch
script-opts=osc-deadzonesize=1,osc-boxalpha=210,osc-scalewindowed=1.2,osc-scalefullscreen=1.2
#osc = no
#border = no

volume = 30

# size constraints relative to screen size. it's WidthxHeight
autofit-larger=100%x97%
autofit-smaller=15%x15%

keep-open=yes # Do not close the window on exit.

# Screenshot #
screenshot-format = png
screenshot-directory = "~/Pictures/Screenshots/"
screenshot-template = "%F %P"
screenshot-png-compression=9
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes

[loop-short]
profile-cond=duration < 15
profile-restore=copy
loop-file

# [audio]
# profile-cond=not vid and vo_configured or p["current-tracks/video/albumart"]
# profile-restore=copy
# osd-margin-y=50
# script-opts=osc-scalewindowed=2.0,osc-scalefullscreen=2.0
# script-opts-add=osc-visibility=always

# [loop-file-dir]
# profile-cond=path:lower():find('.*partofpathinlowercase')
# profile-restore=copy
# loop-file

# [loop-playlist-dir]
# profile-cond=path:lower():find('.*pathpath')
# profile-restore=copy
# loop-playlist=yes

# ytdl-format=bestvideo[height<=?1080]+bestaudio/best
